### ISSUE TITLE
Disperse cards with the same words

### ISSUE THREAD

**Issue by aleksejrs** [Rct567/FrequencyMan#9] opened 2024-06-06 22:41 UTC
I'm getting lots of movies2anki cards like "What?"/"What?!" or "No."/"No!"/No?"/"No, no, no!" next to each other, making them completely useless except for the first one.

**Comment by Rct567** [comment] 2024-06-07 18:29
How exactly do you want FrequencyMan to handle this? My first impression is, it's a 'movies2anki' issue for not generating cards the way you want.

**Comment by aleksejrs** [comment] 2024-06-07 21:27
> How exactly do you want FrequencyMan to handle this?

AnkiMorphs has "[Shift new cards that are not the first to have the unknown morph](https://mortii.github.io/anki-morphs/user_guide/setup/settings/recalc.html)" and [a skip option like MorphMan had](https://mortii.github.io/anki-morphs/user_guide/setup/settings/skip.html).

> My first impression is, it's a 'movies2anki' issue for not generating cards the way you want.

https://github.com/mortii/anki-morphs/issues/216

**Comment by aleksejrs** [comment] 2024-06-21 15:02
It is also about related cards like in the defunct add-ons "[Bury Cousins (related cards that aren't siblings)](https://ankiweb.net/shared/info/1072815885)" and "[Bury related notes](https://ankiweb.net/shared/info/413416269)".

**Comment by Rct567** [comment] 2024-06-21 17:56
I was thinking about creating a "proper introduction" ranking factor. This would basically rank cards by how well suited they are for introducing a word. The best ranking card for a word would have a disproportionately higher score. This would effectively disperse cards with the same new word (while keeping the 'best' at the top, which would be better than arbitrarily dispersing them).

**Comment by Rct567** [comment] 2024-07-06 22:02
I just released a new version with the ranking factors `proper_introduction` and `proper_introduction_dispersed`. Let me know if it works for your situation!

**Comment by aleksejrs** [comment] 2024-07-07 23:46
I added `"ranking_proper_introduction_dispersed": 5.0` to two movies2anki targets.

Searching for `fm_focus_words:*walking* "Target #1"`

The first 4 cards are "Walking man's road...", with due 32904, 32905, 32906, 32907.

They all have the same fm_debug_ranking_info:

```
Target #1
proper_introduction_dispersed: 1.000 x 5.0 = 5.000
familiarity: 0.562 x 2.5 = 1.406
ideal_word_count: 1.000 x 1.0 = 1.000
ideal_focus_word_count: 1.000 x 1.0 = 1.000
familiarity_sweetspot: 0.962 x 1.0 = 0.962
word_frequency: 0.899 x 1.0 = 0.899
most_obscure_word: 0.898 x 0.5 = 0.449
reinforce_focus_words: 1.000 x 0.25 = 0.250
lexical_underexposure: 0.923 x 0.25 = 0.231
lowest_fr_least_familiar_word: 0.914 x 0.25 = 0.229
lowest_word_frequency: 0.899 x 0.25 = 0.225
lowest_familiarity: 0.453 x 0.25 = 0.113
no_new_words: 1.000 x 0.1 = 0.100
proper_introduction: 1.000 x 0.1 = 0.100
```

fm_debug_words_info:

```
Target #1
words_ue_scores: [{'walking': 0.814732072326489, 'road': 0.5999395785897654, 'man': 0.13557324761924922}]
words_fr_scores: [{'man': 0.9602450556036491, 'walking': 0.8647532796164347, 'road': 0.8403143104481587}]
familiarity_sweetspot_scores: [{'walking': 0.9801545257883613, 'road': 0.8981156069966982, 'man': 0.17953721856893307}]
familiarity_scores: [{'man': 2.185001110660068, 'road': 0.3940014289596287, 'walking': 0.1895259259259259}]
```

**Comment by Rct567** [comment] 2024-07-08 13:53
I think that is because there are no new words. Can you confirm? Cards without new words are not effected by this ranking factor. If you scroll through the top of the new cards, do you see any duplicates or 'improper' cards like how you originally reported?

**Comment by aleksejrs** [comment] 2024-07-08 15:38
> I think that is because there are no new words. 
Indeed, there is already a mature card with that line.
However, fm_unseen_words in all those cards is still "walking", although fm_seen_words is "walking, man, road". Those are also the first cards in Target #1 that have fm_unseen_words filled (after 1719 that don't).

> Cards without new words are not effected by this ranking factor.
Usually that's the main problem with cards like "No." 

> If you scroll through the top of the new cards, do you see any duplicates or 'improper' cards like how you originally reported?
The first 82 cards in Target #1 don't even have focus words, but there are duplicates like this:

"♪ I hit the ground ♪"
31208
31209

fm_focus_words:
fm_unseen_words:
fm_seen_words: hit, the, ground
fm_main_focus_word_0:
fm_lowest_fr_word_0: ground
fm_lowest_familiarity_word_0: ground

fm_debug_info:

```
Target #1
fr_scores: 0.896840913631218
ue_scores: 0.417756642730056
familiarity_scores: 0.6752101694915256
familiarity_sweetspot_scores: 0.7904840009885339
proper_introduction_scores: 1
most_obscure_word: ('ground', 0.8965838716121729)
highest_ue_word: ('ground', 0.423439523445395)
ideal_focus_word_count: 0.9
ideal_word_count: 1
lowest_fr_least_familiar_word: ('ground', 0.8965838716121729, 0.7820683978970996)
lowest_fr_word: ('ground', 0.8965838716121729)
ideal_new_words_count_scores: 0.9
```

fm_debug_ranking_info:

```
Target #1
proper_introduction_dispersed: 1.000 x 5.0 = 5.000
familiarity: 0.872 x 2.5 = 2.179
ideal_word_count: 1.000 x 1.0 = 1.000
word_frequency: 0.937 x 1.0 = 0.937
familiarity_sweetspot: 0.890 x 1.0 = 0.890
ideal_focus_word_count: 0.864 x 1.0 = 0.864
most_obscure_word: 0.936 x 0.5 = 0.468
lowest_word_frequency: 0.938 x 0.25 = 0.234
lowest_fr_least_familiar_word: 0.936 x 0.25 = 0.234
lexical_underexposure: 0.555 x 0.25 = 0.139
lowest_familiarity: 0.480 x 0.25 = 0.120
reinforce_focus_words: 0.444 x 0.25 = 0.111
no_new_words: 1.000 x 0.1 = 0.100
proper_introduction: 1.000 x 0.1 = 0.100
```

fm_debug_words_info:
```
Target #1
words_ue_scores: [{'ground': 0.423439523445395, 'hit': 0.22186412180020626, 'the': 0}]
words_fr_scores: [{'the': 1.0, 'hit': 0.9222880735166811, 'ground': 0.8965838716121729}]
familiarity_sweetspot_scores: [{'ground': 0.742416786952032, 'hit': 0.5161408640542793, 'the': 0}]
familiarity_scores: [{'the': 166.2638072948724, 'hit': 1.346043202055984, 'ground': 0.7820683978970996}]
```

**Comment by Rct567** [comment] 2024-07-08 23:31
I just released a new version in which `proper_introduction_dispersed` now also effect cards without new words. Please note that the default ranking factors have also changed a bit. When using `proper_introduction_dispersed`, its best to keep the weight as low as possible while still giving you the desired dispersion.

The field `fm_unseen_words` was renamed in the previous release, but I forgot to add support for the old name. Now `fm_unseen_words` should work again, even though now its called `fm_new_words`.

**Comment by aleksejrs** [comment] 2024-07-09 06:12
> When using `proper_introduction_dispersed`, its best to keep the weight as low as possible while still giving you the desired dispersion.
`Quickly.`
`Quickly!`
`Quickly! Quickly!`
1.1: 1 between the cards
1.5: 1 between the first two, a little more between the last two
1.7: 31202, 31203, 31206

**Comment by Rct567** [comment] 2024-07-09 12:09
I'm going to close this now. Feel free to open a new issue if you encounter any issues, but please provide clear information on what the actual issue is and how to reproduce it.

**Closed by Rct567** 2024-07-09 12:09 UTC
